### Регистрация нового пользователя
POST http://localhost:7000/api/user/signup
Content-Type: application/json

{
    "email": "admin@mail.ru",
    "password": "password123",
    "role": "ADMIN"
}

### Вход в систему (Login)
POST http://localhost:7000/api/user/login
Content-Type: application/json

{
    "email": "admin@mail.ru",
    "password": "password123"
}

### Проверка авторизации (вставь токен из ответа выше после Bearer)
GET http://localhost:7000/api/user/check
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzcyODA2MDc5LCJleHAiOjE3NzI4OTI0Nzl9.HcBSz4y2MrQRyWORtahLs-gCUeHiwcsgRiAfJ6M5QCc